User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'DeprecatePythonPath - experiment'
Error 2021-05-31 13:53:30: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
> python ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2021.2.633441544/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2021-05-31 13:53:33: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-05-31 13:53:34: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-05-31 13:53:34: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-05-31 13:53:34: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-05-31 13:53:34: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-05-31 13:53:34: Failed to parse version from path: python [Error: invalid version python
	at u (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:9:201380)
	at Object.c [as parseVersion] (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:9:200689)
	at f.buildPathEnvInfo (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:78:29613)
	at f.resolveEnv (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:78:29553)
	at E.resolveEnv (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:29:4116)
	at t.PythonEnvsReducer.resolveEnv (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:761268)
	at async t.PythonEnvsResolver.resolveEnv (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:762469)
	at async u.doResolveEnv (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:756609)
	at async H.getInterpreterDetails (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:78:39004)
	at async T.getInterpreterDetails (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:646216)
	at async f.sendTelemetry (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:78:423559)]
Error 2021-05-31 13:53:34: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-05-31 13:53:35: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-05-31 13:53:51: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/jdreeder1/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/jdreeder1/.config/Code/User/settings.json')
	at _handleError (/home/jdreeder1/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:769:473)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:9:298390)
	at async p.doesFileNeedToBeFixed (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:481011)
	at async /home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:480138
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:480084)
	at async p.updateTestSettings (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:479711)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Error 2021-05-31 13:53:51: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/jdreeder1/.vscode/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/jdreeder1/.vscode/settings.json')
	at _handleError (/home/jdreeder1/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:769:473)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:9:298390)
	at async p.doesFileNeedToBeFixed (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:481011)
	at async /home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:480138
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:480084)
	at async p.updateTestSettings (/home/jdreeder1/.vscode-server/extensions/ms-python.python-2021.2.633441544/out/client/extension.js:59:479711)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Starting Jedi language server.
Error 2021-05-31 23:59:26: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-05-31 23:59:27: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-01 00:28:23: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-01 00:28:23: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-02 00:26:25: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-02 00:26:25: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-02 01:05:04: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-02 01:05:04: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-05 17:20:30: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-05 17:20:30: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-06 13:39:31: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-06 13:39:32: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-06 22:08:57: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-06 22:08:57: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-06 22:38:36: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-06 22:38:36: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-07 00:02:54: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-07 00:02:54: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-08 01:04:20: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-08 01:04:20: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-08 01:05:11: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-08 01:05:11: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-08 01:13:17: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-08 01:13:17: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-09 00:37:08: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-09 00:37:08: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-10 00:20:37: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-10 00:20:38: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-13 16:34:11: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-13 16:34:12: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-13 16:37:54: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-13 16:37:54: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-13 23:58:27: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-13 23:58:28: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-15 00:44:04: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-15 00:44:05: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-15 01:46:16: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-15 01:46:16: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-15 01:47:02: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-15 01:47:02: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-15 11:10:10: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
Error 2021-06-15 11:10:10: Failed to resolve symbolic link:  [Error: ENOENT: no such file or directory, lstat 'python3.8'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'python3.8'
}
